version: '3'
services:
  abc_db_local:
    container_name: abc_db_local
    image: library/mariadb:10.3.27
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: abc_local
      MYSQL_USER: abc_user
      MYSQL_PASSWORD: devsecret
      MYSQL_ROOT_PASSWORD: devroot
  abc_db_test:
    container_name: abc_db_test
    image: library/mariadb:10.3.27
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: abc_test
      MYSQL_USER: abc_user
      MYSQL_PASSWORD: testsecret
      MYSQL_ROOT_PASSWORD: testroot